version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: main
    container_name: myapp
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongodb_data: